services:
  stellehosted.dev:
    container_name: "stellehosted.dev"
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - NAVIDROME_URL=${NAVIDROME_URL}
      - NAVIDROME_USER=${NAVIDROME_USER}
      - NAVIDROME_PASSWORD=${NAVIDROME_PASSWORD}
      - NAVIDROME_USERNAME_FILTER=${NAVIDROME_USERNAME_FILTER:-}
    networks:
      - stellehosted.dev
    restart: unless-stopped

  cloudflared:
    container_name: "cloudflared"
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - stellehosted.dev
    restart: unless-stopped

networks:
  stellehosted.dev:
    external: true
