services:
  stellehosted:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: server/.env
    ports:
      - "8090:8080"
    networks:
      - nowplaying
    restart: unless-stopped

networks:
  nowplaying:
    external: true
