services:
  stellehosted.dev:
    container_name: "stellehosted.dev"
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - NAVIDROME_URL=${NAVIDROME_URL}
      - NAVIDROME_USER=${NAVIDROME_USER}
      - NAVIDROME_PASSWORD=${NAVIDROME_PASSWORD}
      - NAVIDROME_USERNAME_FILTER=${NAVIDROME_USERNAME_FILTER:-}
    networks:
      - stellehosted.dev
    ports:
      - 1030:8080
    restart: unless-stopped

networks:
  stellehosted.dev:
    external: true
